/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { GeneratedImageListRelationFilter } from "../../generatedImage/base/GeneratedImageListRelationFilter";
import { GeneratedPageListRelationFilter } from "../../generatedPage/base/GeneratedPageListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { EnumDataFileTypeField } from "./EnumDataFileTypeField";

@InputType()
class DataFileWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  createdBy?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  fileUrl?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GeneratedImageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GeneratedImageListRelationFilter)
  @IsOptional()
  @Field(() => GeneratedImageListRelationFilter, {
    nullable: true,
  })
  generatedImages?: GeneratedImageListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => GeneratedPageListRelationFilter,
  })
  @ValidateNested()
  @Type(() => GeneratedPageListRelationFilter)
  @IsOptional()
  @Field(() => GeneratedPageListRelationFilter, {
    nullable: true,
  })
  generatedPages?: GeneratedPageListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumDataFileTypeField,
  })
  @IsEnum(EnumDataFileTypeField)
  @IsOptional()
  @Field(() => EnumDataFileTypeField, {
    nullable: true,
  })
  typeField?: "Option1";
}

export { DataFileWhereInput as DataFileWhereInput };
