/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { GeneratedImageCreateNestedManyWithoutDataFilesInput } from "./GeneratedImageCreateNestedManyWithoutDataFilesInput";
import { Type } from "class-transformer";
import { GeneratedPageCreateNestedManyWithoutDataFilesInput } from "./GeneratedPageCreateNestedManyWithoutDataFilesInput";
import { EnumDataFileTypeField } from "./EnumDataFileTypeField";

@InputType()
class DataFileCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  createdBy?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fileUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => GeneratedImageCreateNestedManyWithoutDataFilesInput,
  })
  @ValidateNested()
  @Type(() => GeneratedImageCreateNestedManyWithoutDataFilesInput)
  @IsOptional()
  @Field(() => GeneratedImageCreateNestedManyWithoutDataFilesInput, {
    nullable: true,
  })
  generatedImages?: GeneratedImageCreateNestedManyWithoutDataFilesInput;

  @ApiProperty({
    required: false,
    type: () => GeneratedPageCreateNestedManyWithoutDataFilesInput,
  })
  @ValidateNested()
  @Type(() => GeneratedPageCreateNestedManyWithoutDataFilesInput)
  @IsOptional()
  @Field(() => GeneratedPageCreateNestedManyWithoutDataFilesInput, {
    nullable: true,
  })
  generatedPages?: GeneratedPageCreateNestedManyWithoutDataFilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumDataFileTypeField,
  })
  @IsEnum(EnumDataFileTypeField)
  @IsOptional()
  @Field(() => EnumDataFileTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;
}

export { DataFileCreateInput as DataFileCreateInput };
